export const ACTIONS = {
  ON_LOAD_RENDER: 'ON_LOAD_RENDER',
  ON_HOVER_ELEMENTS: 'ON_HOVER_ELEMENTS',
  ON_SELECT_ELEMENT: 'ON_SELECT_ELEMENT',
  ON_SELECT_FROM_LEFT_PANEL: 'ON_SELECT_FROM_LEFT_PANEL',
  ON_CHANGE_VALUE: 'ON_CHANGE_VALUE'
}
